spring:
  datasource:
    url: jdbc:mysql://${MYSQL_PROD_URL}:3306/${MYSQL_DATABASE}
    username: ${MYSQL_PROD_USER}
    password: ${MYSQL_PROD_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: redis
      port: 6379
  security:
    oauth2:
<<<<<<< HEAD
      redirect-url: http://localhost:5173/oauth2/redirect # 개발기간동안 임시로 localhost로 리다이렉트한다.
=======
      redirect-dev-url: http://localhost:5173/oauth2/redirect
      redirect-prod-url: https://www.splanet.co.kr/oauth2/redirect
      origin-dev: localhost
      origin-prod: splanet.co.kr
>>>>>>> weekly/11
      client:
        registration:
          kakao:
            redirect-uri: https://api.splanet.co.kr/login/oauth2/code/kakao
<<<<<<< HEAD
=======

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: OFF
>>>>>>> weekly/11
